apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: todo-api
          env:
            - name: TODO_HTTP_ADDR
              value: ":8080"
            - name: TODO_GRPC_ADDR
              value: ":9090"
            - name: TODO_DB_DSN
              value: "postgres://todo:todo@postgres:5432/todo?sslmode=disable"
            - name: TODO_WORKERS
              value: "4"
          ports:
            - containerPort: 8080
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api
spec:
  selector:
    app: todo-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 9090
      targetPort: 9090