apiVersion: v1
kind: Secret
metadata:
  name: todo-api-secret
  namespace: todo-prod
  labels:
    app: todo-api

type: Opaque
stringData:
  TODO_DB_DSN: "postgres://todo:todo@todo-postgres.todo-prod.svc.cluster.local:5432/todo?sslmode=disable"